# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Song.delete_all

Song.create(name: '420', abbreviation: '420', length: 4.4)
Song.create(name: '1759', abbreviation: '1759', length: 9.7)
Song.create(name: '12 Wolves', abbreviation: 'Wolves', length: 11.5)
Song.create(name: 'Acadian Driftwood', abbreviation: 'Drftwd', length: 8.5)
Song.create(name: 'All Alone', abbreviation: 'Alone', length: 8.9)
Song.create(name: 'All That\'s Dead', abbreviation: 'AllThats', length: 2.7)
Song.create(name: 'Any Road', abbreviation: 'AnyRoad', length: 4.6)
Song.create(name: 'Been Down That Road', abbreviation: 'BDTR', length: 5.7)
Song.create(name: 'Berkeley Flash', abbreviation: 'Berk', length: 9)
Song.create(name: 'Bird in a House', abbreviation: 'Bird', length: 7.6)
Song.create(name: 'Birds of America', abbreviation: 'BOA', length: 13.4)
Song.create(name: 'Black Bear', abbreviation: 'Bear', length: 11.7)
Song.create(name: 'Black Elk Speaks', abbreviation: 'Elk', length: 6.7)
Song.create(name: 'Blazin\' a Trail', abbreviation: 'Blazin', length: 5)
Song.create(name: 'Bluegrass Breakdown', abbreviation: 'Brkdwn', length: 5.6)
Song.create(name: 'Bowling Green', abbreviation: 'BlGreen', length: 3.3)
Song.create(name: 'Bread and Water', abbreviation: 'B&W', length: 4.5)
Song.create(name: 'Bringin\' My Baby Back Home', abbreviation: 'Babyback', length: 5.2)
Song.create(name: 'Brown Co Breakdown', abbreviation: 'BrCoBrk', length: 3.4)
Song.create(name: 'Butterfly and the Tree', abbreviation: 'Butterfly', length: 7.2)
Song.create(name: 'Came Up Smilin', abbreviation: 'Smilin', length: 6.2)
Song.create(name: 'Captain Nowhere', abbreviation: 'Capn', length: 10)
Song.create(name: 'Carrying Coal to Newcastle', abbreviation: 'Coal', length: 7.6)
Song.create(name: 'Catfish John', abbreviation: 'Catfish', length: 7.6)
Song.create(name: 'Chains', abbreviation: 'Chains', length: 5.4)
Song.create(name: 'Cold Water', abbreviation: 'CdWater', length: 4.5)
Song.create(name: 'Colorado', abbreviation: 'CO', length: 9.3)
Song.create(name: 'Crossing the Gap', abbreviation: 'Gap', length: 4.4)
Song.create(name: 'Cuckoo, The', abbreviation: 'Cuckoo', length: 8.5)
Song.create(name: 'Cuckoo\'s Medley, The', abbreviation: 'Cukmed', length: 10.3)
Song.create(name: 'Dance Around Molly>Dandelion Wine', abbreviation: 'DAM>DW', length: 7.7)
Song.create(name: 'Dance Around Molly', abbreviation: 'Molly', length: 2.6)
Song.create(name: 'Dandelion Wine', abbreviation: 'Dandy', length: 5)
Song.create(name: 'Day on the Sand', abbreviation: 'Sand', length: 4.5)
Song.create(name: 'Dies Irae', abbreviation: 'Irae', length: 1.6)
Song.create(name: 'Donkey for Sale', abbreviation: 'Donkey', length: 9.2)
Song.create(name: 'Dover to Dunkirk', abbreviation: 'Dover', length: 7)
Song.create(name: 'Drag Him Down', abbreviation: 'Drag', length: 6.1)
Song.create(name: 'Duncan and Brady', abbreviation: 'D&B', length: 6.1)
Song.create(name: 'El Cumbanchero', abbreviation: 'ElCum', length: 6.7)
Song.create(name: 'Elko', abbreviation: 'Elko', length: 9.3)
Song.create(name: 'Everything Comes Together', abbreviation: 'Ething', length: 8.2)
Song.create(name: 'Face with a Hole', abbreviation: 'Face', length: 8.2)
Song.create(name: 'Fairwell to Isinglass', abbreviation: 'Isin', length: 4.6)
Song.create(name: 'Fiddlee', abbreviation: 'Fiddlee', length: 6)
Song.create(name: 'Fisherman\'s Blues', abbreviation: 'Fishers', length: 6.9)
Song.create(name: 'Flower Between the Stones', abbreviation: 'Flower', length: 5.8)
Song.create(name: 'For Love', abbreviation: '4Love', length: 7.3)
Song.create(name: 'Forecast, The', abbreviation: 'Forecast', length: 10.3)
Song.create(name: 'Game Band Strut', abbreviation: 'Strut', length: 5)
Song.create(name: 'Genesis', abbreviation: 'Genesis', length: 9)
Song.create(name: 'Give that Boy a Hand', abbreviation: 'Boy', length: 4.8)
Song.create(name: 'Goat', abbreviation: 'Goat', length: 11)
Song.create(name: 'Gold Rush', abbreviation: 'Grush', length: 6.4)
Song.create(name: 'Gone to the Feilds', abbreviation: 'Fields', length: 6)
Song.create(name: 'Good Life, The', abbreviation: 'Glife', length: 6.7)
Song.create(name: 'Grandfather Mountain', abbreviation: 'Gfather', length: 12)
Song.create(name: 'Hangtown Ball', abbreviation: 'Htown', length: 10.1)
Song.create(name: 'Happy Song', abbreviation: 'Happy', length: 3.9)
Song.create(name: 'Hard Livin', abbreviation: 'Livin', length: 9.6)
Song.create(name: 'Harvest Moon', abbreviation: 'Hmoon', length: 8.6)
Song.create(name: 'Head', abbreviation: 'Head', length: 15.2)
Song.create(name: 'Hot \'Lanta', abbreviation: 'H\’Lanta', length: 7.3)
Song.create(name: 'Hunting Song, The', abbreviation: 'Hunt', length: 11.3)
Song.create(name: 'If You Will Be My Lady', abbreviation: 'Lady', length: 5)
Song.create(name: 'In Paradisum', abbreviation: 'Para', length: 4.5)
Song.create(name: 'In the Basement', abbreviation: 'Bsmnt', length: 5.4)
Song.create(name: 'Introit', abbreviation: 'Shire', length: 2.6)
Song.create(name: 'Jerusalem Ridge', abbreviation: 'Jridge', length: 7.8)
Song.create(name: 'Jupiter and the 119', abbreviation: 'Jup', length: 7.9)
Song.create(name: 'Just So You Know', abbreviation: 'JSYK', length: 7.7)
Song.create(name: 'Keep Movin\' On', abbreviation: 'MvnOn', length: 7.5)
Song.create(name: 'Lacrimosa', abbreviation: 'Lacrim', length: 2.6)
Song.create(name: 'Last of the Outlaws', abbreviation: 'LOTO', length: 7.8)
Song.create(name: 'Like a Buddha', abbreviation: 'Buddha', length: 13.9)
Song.create(name: 'Little Bit O\' Me', abbreviation: 'LilBit', length: 7.9)
Song.create(name: 'Little Rabbit', abbreviation: 'Rabbit', length: 6.7)
Song.create(name: 'Lois Ann', abbreviation: 'Lois', length: 4)
Song.create(name: 'Lonecroft Farewell', abbreviation: 'LCF', length: 7.5)
Song.create(name: 'Lonecroft Ramble', abbreviation: 'LCR', length: 4)
Song.create(name: 'Long Walk Home', abbreviation: 'LWH', length: 5.4)
Song.create(name: 'Long Way to Go', abbreviation: 'LWTG', length: 6.5)
Song.create(name: 'Lordy, Lordy', abbreviation: 'Lordy', length: 4.5)
Song.create(name: 'Lovin\' You', abbreviation: 'LovinU', length: 4.7)
Song.create(name: 'Luxury Liner', abbreviation: 'Lux', length: 8.5)
Song.create(name: 'Magic Foot', abbreviation: 'Foot', length: 3.6)
Song.create(name: 'Mess', abbreviation: 'Mess', length: 15)
Song.create(name: 'Midnight Special', abbreviation: 'MdnSpc', length: 7.9)
Song.create(name: 'Mighty River', abbreviation: 'River', length: 7.5)
Song.create(name: 'Mission Man', abbreviation: 'MM', length: 11.6)
Song.create(name: 'Mississippi Half Step', abbreviation: '1/2Step', length: 9.7)
Song.create(name: 'Monkey', abbreviation: 'Monkey', length: 4.1)
Song.create(name: 'Moonshiner', abbreviation: 'Shiner', length: 6.5)
Song.create(name: 'Mountain Time', abbreviation: 'MtTime', length: 9.2)
Song.create(name: 'Mourning Flies', abbreviation: 'Flies', length: 9.8)
Song.create(name: 'My Sisters and Brothers', abbreviation: 'SisBro', length: 8.8)
Song.create(name: 'Neath the Stars', abbreviation: 'Stars', length: 4.5)
Song.create(name: 'New Lee Highway Blues', abbreviation: 'NewLee', length: 6.8)
Song.create(name: 'Old Dangerfield', abbreviation: 'Danger', length: 6.8)
Song.create(name: 'Old Man and the Land', abbreviation: 'Oman', length: 6.9)
Song.create(name: 'On the Banks', abbreviation: 'Banks', length: 6)
Song.create(name: 'Only by the Light', abbreviation: 'OBTL', length: 7)
Song.create(name: 'One More Night on the Road', abbreviation: '1More', length: 5.9)
Song.create(name: 'Pack a Day', abbreviation: 'Pack', length: 3.4)
Song.create(name: 'Peace on Earth', abbreviation: 'Peace', length: 3.4)
Song.create(name: 'Peggy-O', abbreviation: 'Peggy', length: 8)
Song.create(name: 'Potter\'s Feild', abbreviation: 'Pot', length: 6.3)
Song.create(name: 'Powderfinger', abbreviation: 'PwdFng', length: 9.4)
Song.create(name: 'Railroad Earth', abbreviation: 'RRE', length: 6.5)
Song.create(name: 'Raindance', abbreviation: 'Raindc', length: 6.4)
Song.create(name: 'Raven\'s Child', abbreviation: 'Raven', length: 6)
Song.create(name: 'Real Love', abbreviation: 'RealLuv', length: 5.6)
Song.create(name: 'Reuben\'s Train', abbreviation: 'Reuben', length: 7.3)
Song.create(name: 'Right in Tune', abbreviation: 'Tune', length: 5)
Song.create(name: 'Roadhouse Blues', abbreviation: 'RdHouse', length: 8.4)
Song.create(name: 'RV', abbreviation: 'RV', length: 5.4)
Song.create(name: 'Saddle of the Sun', abbreviation: 'Saddle', length: 5.2)
Song.create(name: 'Said What you Mean', abbreviation: 'SWYM', length: 6.6)
Song.create(name: 'Seven Story Mountain', abbreviation: '7SM', length: 14.4)
Song.create(name: 'Shockenawe Mountain', abbreviation: 'Shock', length: 2.8)
Song.create(name: 'Sing for Me', abbreviation: 'Sing', length: 5.3)
Song.create(name: 'Soul of a Man', abbreviation: 'Soul', length: 5.2)
Song.create(name: 'Spring-heeled Jack', abbreviation: 'SHJ', length: 14)
Song.create(name: 'Standing on the Corner', abbreviation: 'Corner', length: 9.6)
Song.create(name: 'Still Water Get Away', abbreviation: 'Swat', length: 9.1)
Song.create(name: 'Storms', abbreviation: 'Storms', length: 6.4)
Song.create(name: 'Take a Bow', abbreviation: 'Bow', length: 7)
Song.create(name: 'Take the Skinheads Bowling', abbreviation: 'Sknhead', length: 6.4)
Song.create(name: 'Terrapin Station', abbreviation: 'Terrapin', length: 12.7)
Song.create(name: 'Through the Gates', abbreviation: 'Gates', length: 2.1)
Song.create(name: 'Too Much Information', abbreviation: 'TMI', length: 5.9)
Song.create(name: 'Tore Up Over You', abbreviation: 'Toreup', length: 6.8)
Song.create(name: 'Tuba Mirum', abbreviation: 'Hape', length: 7.1)
Song.create(name: 'Walk Beside Me', abbreviation: 'TO\’B', length: 6.5)
Song.create(name: 'Walls of Time', abbreviation: 'Walls', length: 8.4)
Song.create(name: 'Warhead Boogie', abbreviation: 'Warhead', length: 12.5)
Song.create(name: 'Waterfountain Quicksand', abbreviation: 'WFQS', length: 4.5)
Song.create(name: 'Wavin\' Willy', abbreviation: 'Wavin', length: 4.6)
Song.create(name: 'Wayfaring Stranger', abbreviation: 'Wayfar', length: 7.2)
Song.create(name: 'Wheel, The', abbreviation: 'Wheel', length: 10.8)
Song.create(name: 'When the Sun Gets in Your Blood', abbreviation: 'Sblood', length: 7.4)
Song.create(name: 'Where Songs Begin', abbreviation: 'Songs', length: 8.1)
Song.create(name: 'Woyia Minor Key', abbreviation: 'MinKey', length: 5.3)
Song.create(name: 'You Never Know', abbreviation: 'YNK', length: 6.9)

